openapi: 3.0.0
info:
  title: Minimal Petstore (Example)
  version: 1.0.0
paths:
  /pet/{petId}:
    get:
      operationId: getPetById
      summary: Get pet by id
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: ok

